// Massive Internet Directory Database
// Includes design inspiration sites (httpster-style) + utility sites
// Last updated: Dec 18, 2025 - Added 100+ portfolio sites & fixed Amazon links

const categories = [
  // ========== DESIGN & CREATIVE ==========
  {
    id: 'design-studios',
    name: 'design studios',
    icon: 'Palette',
    sites: [
      { title: 'Pentagram', url: 'https://www.pentagram.com/', description: 'legendary design firm' },
      { title: 'IDEO', url: 'https://www.ideo.com/', description: 'design thinking pioneers' },
      { title: 'Sagmeister & Walsh', url: 'https://sagmeisterwalsh.com/', description: 'creative studio' },
      { title: 'Collins', url: 'https://www.wearecollins.com/', description: 'brand experience' },
      { title: 'Huge', url: 'https://www.hugeinc.com/', description: 'digital agency' },
      { title: 'Fantasy', url: 'https://fantasy.co/', description: 'product design' },
      { title: 'ueno', url: 'https://ueno.co/', description: 'digital agency' },
      { title: 'Work & Co', url: 'https://work.co/', description: 'digital products' },
      { title: 'Instrument', url: 'https://www.instrument.com/', description: 'digital creative' },
      { title: 'Basic Agency', url: 'https://www.basicagency.com/', description: 'brand agency' },
      { title: 'Locomotive', url: 'https://locomotive.ca/', description: 'interactive studio' },
      { title: 'Active Theory', url: 'https://activetheory.net/', description: 'webgl experiences' },
      { title: 'ManvsMachine', url: 'https://mvsm.com/', description: 'motion design' },
      { title: 'Buck', url: 'https://buck.co/', description: 'production company' },
      { title: 'Resn', url: 'https://resn.co.nz/', description: 'digital experiences' },
      { title: 'Jam3', url: 'https://www.jam3.com/', description: 'digital production' },
      { title: 'North Kingdom', url: 'https://www.northkingdom.com/', description: 'digital storytelling' },
      { title: 'Hello Monday', url: 'https://www.hellomonday.com/', description: 'creative agency' },
      { title: 'MediaMonks', url: 'https://www.mediamonks.com/', description: 'creative production' },
      { title: 'Dogstudio', url: 'https://dogstudio.co/', description: 'creative agency' },
      { title: 'Unfold', url: 'https://unfold.no/', description: 'design studio' },
      { title: 'Rally Interactive', url: 'https://rallyinteractive.com/', description: 'digital agency' },
      { title: 'Haus', url: 'https://madeinhaus.com/', description: 'design studio' },
      { title: 'Upperquad', url: 'https://upperquad.com/', description: 'digital studio' },
      { title: 'Metalab', url: 'https://www.metalab.com/', description: 'product studio' },
      { title: 'Elegant Seagulls', url: 'https://elegantseagulls.com/', description: 'digital agency' },
      { title: 'Build in Amsterdam', url: 'https://www.buildinamsterdam.com/', description: 'creative agency' },
      { title: 'Frog Design', url: 'https://www.frog.co/', description: 'design consultancy' },
      { title: 'Futura', url: 'https://futura.cl/', description: 'design studio' },
      { title: 'Studio Freight', url: 'https://studiofreight.com/', description: 'digital studio' },
    ]
  },
  {
    id: 'design-inspiration',
    name: 'design inspiration',
    icon: 'Sparkles',
    sites: [
      { title: 'Awwwards', url: 'https://www.awwwards.com/', description: 'best websites' },
      { title: 'Httpster', url: 'https://httpster.net/', description: 'minimal inspiration' },
      { title: 'Godly', url: 'https://godly.website/', description: 'astronomical sites' },
      { title: 'Siteinspire', url: 'https://www.siteinspire.com/', description: 'web design showcase' },
      { title: 'Brutalist Websites', url: 'https://brutalistwebsites.com/', description: 'raw web' },
      { title: 'One Page Love', url: 'https://onepagelove.com/', description: 'single page sites' },
      { title: 'Land-book', url: 'https://land-book.com/', description: 'landing pages' },
      { title: 'Lapa Ninja', url: 'https://www.lapa.ninja/', description: 'landing page gallery' },
      { title: 'Minimal Gallery', url: 'https://minimal.gallery/', description: 'minimal designs' },
      { title: 'Footer Design', url: 'https://www.footer.design/', description: 'footer inspiration' },
      { title: 'SaaS Landing Page', url: 'https://saaslandingpage.com/', description: 'saas design' },
      { title: 'Dribbble', url: 'https://dribbble.com/', description: 'design community' },
      { title: 'Behance', url: 'https://www.behance.net/', description: 'creative portfolios' },
      { title: 'The FWA', url: 'https://thefwa.com/', description: 'cutting edge' },
      { title: 'CSS Design Awards', url: 'https://www.cssdesignawards.com/', description: 'css excellence' },
      { title: 'siteInspire', url: 'https://www.siteinspire.com/', description: 'web inspiration' },
      { title: 'WebDesign Inspiration', url: 'https://www.webdesign-inspiration.com/', description: 'curated sites' },
      { title: 'Dark Mode Design', url: 'https://www.darkmodedesign.com/', description: 'dark interfaces' },
      { title: 'Muzli', url: 'https://muz.li/', description: 'design inspiration' },
      { title: 'Mobbin', url: 'https://mobbin.com/', description: 'mobile patterns' },
      { title: 'Screenlane', url: 'https://screenlane.com/', description: 'ui inspiration' },
      { title: 'UI Sources', url: 'https://www.uisources.com/', description: 'real app flows' },
      { title: 'Collect UI', url: 'https://collectui.com/', description: 'daily ui' },
      { title: 'Page Flows', url: 'https://pageflows.com/', description: 'user flow videos' },
      { title: 'Refero', url: 'https://refero.design/', description: 'design references' },
    ]
  },
  {
    id: 'typography',
    name: 'typography & fonts',
    icon: 'Type',
    sites: [
      { title: 'Typewolf', url: 'https://www.typewolf.com/', description: 'font recommendations' },
      { title: 'Fonts In Use', url: 'https://fontsinuse.com/', description: 'typography archive' },
      { title: 'Google Fonts', url: 'https://fonts.google.com/', description: 'free fonts' },
      { title: 'Font Squirrel', url: 'https://www.fontsquirrel.com/', description: 'free fonts' },
      { title: 'DaFont', url: 'https://www.dafont.com/', description: 'font archive' },
      { title: 'FontSpace', url: 'https://www.fontspace.com/', description: 'free fonts' },
      { title: 'Adobe Fonts', url: 'https://fonts.adobe.com/', description: 'premium fonts' },
      { title: 'Fontshare', url: 'https://www.fontshare.com/', description: 'free quality fonts' },
      { title: 'Velvetyne', url: 'https://velvetyne.fr/', description: 'libre fonts' },
      { title: 'UNCUT', url: 'https://uncut.wtf/', description: 'free typefaces' },
      { title: 'Open Foundry', url: 'https://open-foundry.com/', description: 'open source fonts' },
      { title: 'The League of Moveable Type', url: 'https://www.theleagueofmoveabletype.com/', description: 'open source fonts' },
      { title: 'Pangram Pangram', url: 'https://pangrampangram.com/', description: 'type foundry' },
      { title: 'Grilli Type', url: 'https://www.grillitype.com/', description: 'swiss type foundry' },
      { title: 'Klim Type', url: 'https://klim.co.nz/', description: 'type foundry' },
      { title: 'Commercial Type', url: 'https://commercialtype.com/', description: 'type foundry' },
      { title: 'Colophon Foundry', url: 'https://www.colophon-foundry.org/', description: 'type foundry' },
      { title: 'Future Fonts', url: 'https://www.futurefonts.xyz/', description: 'fonts in progress' },
      { title: 'Type Network', url: 'https://typenetwork.com/', description: 'font platform' },
      { title: 'Atipo Foundry', url: 'https://www.atipofoundry.com/', description: 'type foundry' },
    ]
  },
  {
    id: 'colors',
    name: 'colors & palettes',
    icon: 'Palette',
    sites: [
      { title: 'Color Hunt', url: 'https://colorhunt.co/', description: 'color palettes' },
      { title: 'Coolors', url: 'https://coolors.co/', description: 'palette generator' },
      { title: 'Adobe Color', url: 'https://color.adobe.com/', description: 'color wheel' },
      { title: 'Khroma', url: 'https://www.khroma.co/', description: 'ai color tool' },
      { title: 'Colormind', url: 'http://colormind.io/', description: 'ai colors' },
      { title: 'Happy Hues', url: 'https://www.happyhues.co/', description: 'color palettes' },
      { title: 'Muzli Colors', url: 'https://colors.muz.li/', description: 'color generator' },
      { title: 'Picular', url: 'https://picular.co/', description: 'google colors' },
      { title: 'ColorSpace', url: 'https://mycolor.space/', description: 'gradient generator' },
      { title: 'Gradient Hunt', url: 'https://gradienthunt.com/', description: 'gradients' },
      { title: 'uiGradients', url: 'https://uigradients.com/', description: 'gradient collection' },
      { title: 'WebGradients', url: 'https://webgradients.com/', description: 'css gradients' },
      { title: 'Eggradients', url: 'https://www.eggradients.com/', description: 'gradient backgrounds' },
      { title: 'Grabient', url: 'https://www.grabient.com/', description: 'gradient maker' },
      { title: 'CSS Gradient', url: 'https://cssgradient.io/', description: 'gradient generator' },
      { title: 'Paletton', url: 'https://paletton.com/', description: 'color scheme designer' },
      { title: 'Color Designer', url: 'https://colordesigner.io/', description: 'color tools' },
      { title: 'Colour Lovers', url: 'https://www.colourlovers.com/', description: 'color community' },
      { title: 'Realtime Colors', url: 'https://www.realtimecolors.com/', description: 'visualize colors' },
      { title: 'Huemint', url: 'https://huemint.com/', description: 'ai palette generator' },
    ]
  },
  {
    id: 'illustration',
    name: 'illustrations & graphics',
    icon: 'Brush',
    sites: [
      { title: 'unDraw', url: 'https://undraw.co/', description: 'svg illustrations' },
      { title: 'DrawKit', url: 'https://www.drawkit.com/', description: 'free illustrations' },
      { title: 'Humaaans', url: 'https://www.humaaans.com/', description: 'people illustrations' },
      { title: 'Open Peeps', url: 'https://www.openpeeps.com/', description: 'hand-drawn people' },
      { title: 'Blush', url: 'https://blush.design/', description: 'illustrations' },
      { title: 'Storyset', url: 'https://storyset.com/', description: 'animated illustrations' },
      { title: 'Absurd Design', url: 'https://absurd.design/', description: 'surreal illustrations' },
      { title: 'Illustrations.co', url: 'https://illlustrations.co/', description: 'open source illustrations' },
      { title: 'Lukasz Adam', url: 'https://lukaszadam.com/illustrations', description: 'free svg' },
      { title: 'ManyPixels', url: 'https://www.manypixels.co/gallery', description: 'illustration gallery' },
      { title: 'Glaze', url: 'https://www.glazestock.com/', description: 'illustrations' },
      { title: 'Stubborn', url: 'https://stubborn.fun/', description: 'character generator' },
      { title: 'Fresh Folk', url: 'https://fresh-folk.com/', description: 'people illustrations' },
      { title: 'Control', url: 'https://control.rocks/', description: 'illustration library' },
      { title: 'Smash Illustrations', url: 'https://usesmash.com/', description: 'construction kit' },
      { title: 'Open Doodles', url: 'https://www.opendoodles.com/', description: 'sketchy illustrations' },
      { title: 'Pixeltrue', url: 'https://www.pixeltrue.com/illustrations', description: 'free illustrations' },
      { title: 'Avataaars', url: 'https://avataaars.com/', description: 'avatar generator' },
      { title: 'Big Heads', url: 'https://bigheads.io/', description: 'avatar illustrations' },
      { title: 'Error 404', url: 'https://error404.fun/', description: '404 illustrations' },
    ]
  },
  {
    id: 'icons',
    name: 'icons & symbols',
    icon: 'Sparkles',
    sites: [
      { title: 'Feather Icons', url: 'https://feathericons.com/', description: 'simple icons' },
      { title: 'Heroicons', url: 'https://heroicons.com/', description: 'tailwind icons' },
      { title: 'Lucide', url: 'https://lucide.dev/', description: 'icon toolkit' },
      { title: 'Phosphor Icons', url: 'https://phosphoricons.com/', description: 'flexible icons' },
      { title: 'Tabler Icons', url: 'https://tabler-icons.io/', description: 'svg icons' },
      { title: 'Iconoir', url: 'https://iconoir.com/', description: 'open source icons' },
      { title: 'Remix Icon', url: 'https://remixicon.com/', description: 'icon system' },
      { title: 'Bootstrap Icons', url: 'https://icons.getbootstrap.com/', description: 'bootstrap icons' },
      { title: 'Font Awesome', url: 'https://fontawesome.com/', description: 'icon library' },
      { title: 'Material Icons', url: 'https://fonts.google.com/icons', description: 'google icons' },
      { title: 'Ionicons', url: 'https://ionic.io/ionicons', description: 'ionic icons' },
      { title: 'css.gg', url: 'https://css.gg/', description: 'css icons' },
      { title: 'Simple Icons', url: 'https://simpleicons.org/', description: 'brand icons' },
      { title: 'SVG Repo', url: 'https://www.svgrepo.com/', description: 'svg vectors' },
      { title: 'Iconmonstr', url: 'https://iconmonstr.com/', description: 'free icons' },
      { title: 'Flaticon', url: 'https://www.flaticon.com/', description: 'icon database' },
      { title: 'The Noun Project', url: 'https://thenounproject.com/', description: 'icon marketplace' },
      { title: 'Icons8', url: 'https://icons8.com/', description: 'icons & illustrations' },
      { title: '3D Icons', url: 'https://3dicons.co/', description: '3d icons' },
      { title: 'Lordicon', url: 'https://lordicon.com/', description: 'animated icons' },
    ]
  },
  {
    id: 'ui-components',
    name: 'ui components',
    icon: 'Code',
    sites: [
      { title: 'shadcn/ui', url: 'https://ui.shadcn.com/', description: 'react components' },
      { title: 'Radix UI', url: 'https://www.radix-ui.com/', description: 'headless components' },
      { title: 'Headless UI', url: 'https://headlessui.com/', description: 'unstyled components' },
      { title: 'Chakra UI', url: 'https://chakra-ui.com/', description: 'react components' },
      { title: 'Ant Design', url: 'https://ant.design/', description: 'enterprise ui' },
      { title: 'Material UI', url: 'https://mui.com/', description: 'react components' },
      { title: 'Mantine', url: 'https://mantine.dev/', description: 'react components' },
      { title: 'NextUI', url: 'https://nextui.org/', description: 'react ui library' },
      { title: 'Daisy UI', url: 'https://daisyui.com/', description: 'tailwind components' },
      { title: 'Flowbite', url: 'https://flowbite.com/', description: 'tailwind components' },
      { title: 'Preline', url: 'https://preline.co/', description: 'tailwind ui' },
      { title: 'Tailwind UI', url: 'https://tailwindui.com/', description: 'premium components' },
      { title: 'Meraki UI', url: 'https://merakiui.com/', description: 'tailwind components' },
      { title: 'Hyper UI', url: 'https://www.hyperui.dev/', description: 'tailwind components' },
      { title: 'Aceternity UI', url: 'https://ui.aceternity.com/', description: 'animated components' },
      { title: 'Magic UI', url: 'https://magicui.design/', description: 'animated components' },
      { title: 'Animata', url: 'https://animata.design/', description: 'animated tailwind' },
      { title: 'cult/ui', url: 'https://www.cult-ui.com/', description: 'component collection' },
      { title: 'Syntax UI', url: 'https://syntaxui.com/', description: 'free components' },
      { title: 'Tremor', url: 'https://www.tremor.so/', description: 'dashboard components' },
    ]
  },
  {
    id: 'design-tools',
    name: 'design tools',
    icon: 'Wrench',
    sites: [
      { title: 'Figma', url: 'https://www.figma.com/', description: 'collaborative design' },
      { title: 'Framer', url: 'https://www.framer.com/', description: 'web builder' },
      { title: 'Sketch', url: 'https://www.sketch.com/', description: 'mac design' },
      { title: 'Adobe XD', url: 'https://www.adobe.com/products/xd.html', description: 'ui design' },
      { title: 'Penpot', url: 'https://penpot.app/', description: 'open source design' },
      { title: 'Canva', url: 'https://www.canva.com/', description: 'easy design' },
      { title: 'Lunacy', url: 'https://icons8.com/lunacy', description: 'free design app' },
      { title: 'Affinity Designer', url: 'https://affinity.serif.com/designer/', description: 'vector design' },
      { title: 'Vectornator', url: 'https://www.vectornator.io/', description: 'free vector app' },
      { title: 'Spline', url: 'https://spline.design/', description: '3d design' },
      { title: 'Vectary', url: 'https://www.vectary.com/', description: '3d design tool' },
      { title: 'Rive', url: 'https://rive.app/', description: 'interactive animations' },
      { title: 'Lottie', url: 'https://lottiefiles.com/', description: 'animations' },
      { title: 'Principle', url: 'https://principleformac.com/', description: 'prototyping' },
      { title: 'ProtoPie', url: 'https://www.protopie.io/', description: 'advanced prototypes' },
      { title: 'InVision', url: 'https://www.invisionapp.com/', description: 'prototyping' },
      { title: 'Marvel', url: 'https://marvelapp.com/', description: 'design platform' },
      { title: 'Zeplin', url: 'https://zeplin.io/', description: 'design handoff' },
      { title: 'Avocode', url: 'https://avocode.com/', description: 'design collaboration' },
      { title: 'Overflow', url: 'https://overflow.io/', description: 'user flow diagrams' },
    ]
  },
  // ========== ARCHITECTURE & PHOTOGRAPHY ==========
  {
    id: 'architecture',
    name: 'architecture',
    icon: 'Home',
    sites: [
      { title: 'ArchDaily', url: 'https://www.archdaily.com/', description: 'architecture news' },
      { title: 'Dezeen', url: 'https://www.dezeen.com/', description: 'design magazine' },
      { title: 'Designboom', url: 'https://www.designboom.com/', description: 'design news' },
      { title: 'Architizer', url: 'https://architizer.com/', description: 'architecture database' },
      { title: 'Divisare', url: 'https://divisare.com/', description: 'architecture atlas' },
      { title: 'Arch2O', url: 'https://www.arch2o.com/', description: 'architecture' },
      { title: 'Afasia Archzine', url: 'https://afasiaarchzine.com/', description: 'architecture blog' },
      { title: 'World Architects', url: 'https://www.world-architects.com/', description: 'architect profiles' },
      { title: 'Architecture Foundation', url: 'https://www.architecturefoundation.org.uk/', description: 'uk architecture' },
      { title: 'Snøhetta', url: 'https://snohetta.com/', description: 'architecture studio' },
      { title: 'BIG', url: 'https://big.dk/', description: 'bjarke ingels group' },
      { title: 'Zaha Hadid', url: 'https://www.zaha-hadid.com/', description: 'architecture firm' },
      { title: 'Foster + Partners', url: 'https://www.fosterandpartners.com/', description: 'architecture' },
      { title: 'OMA', url: 'https://oma.eu/', description: 'rem koolhaas' },
      { title: 'Heatherwick', url: 'https://www.heatherwick.com/', description: 'design studio' },
      // Lowkey & Underrated Studios
      { title: 'Studio MEMM', url: 'https://studiomemm.com/', description: 'nature-integrated asymmetry' },
      { title: 'Patchwork Architecture', url: 'https://patchworkarchitecture.co.nz/', description: 'bold textured nz vibes' },
      { title: 'Makhno Studio', url: 'https://makhnostudio.com/', description: 'ukrainian cultural fusion' },
      { title: 'Raad Studio', url: 'https://raad.studio/', description: 'experimental layouts' },
      { title: 'Robert Gurney', url: 'https://www.robertgurneyarchitect.com/', description: 'modern residential' },
      { title: 'Ark Shelter', url: 'https://www.arkshelter.com/', description: 'eco-modular aesthetic' },
      { title: 'Emmanuelle Moureaux', url: 'https://www.emmanuellemoureaux.com/', description: 'colorful installations' },
      { title: 'MVRDV', url: 'https://www.mvrdv.nl/', description: 'dutch innovation' },
      { title: 'Kengo Kuma', url: 'https://kkaa.co.jp/', description: 'japanese minimalism' },
      { title: 'Tadao Ando', url: 'https://www.tadao-ando.com/', description: 'concrete poetry' },
      { title: 'Olson Kundig', url: 'https://olsonkundig.com/', description: 'craft-driven design' },
      { title: 'Studio Gang', url: 'https://studiogang.com/', description: 'chicago innovation' },
      { title: 'Morphosis', url: 'https://www.morphosis.com/', description: 'thom mayne studio' },
      { title: 'Diller Scofidio', url: 'https://dsrny.com/', description: 'interdisciplinary design' },
      { title: 'Atelier Bow-Wow', url: 'https://www.bow-wow.jp/', description: 'tokyo micro architecture' },
    ]
  },
  {
    id: 'photography',
    name: 'art & photography',
    icon: 'Image',
    sites: [
      { title: 'Unsplash', url: 'https://unsplash.com/', description: 'free photos' },
      { title: 'Pexels', url: 'https://www.pexels.com/', description: 'free stock photos' },
      { title: 'Pixabay', url: 'https://pixabay.com/', description: 'free images' },
      { title: 'Burst', url: 'https://burst.shopify.com/', description: 'free photos' },
      { title: 'StockSnap', url: 'https://stocksnap.io/', description: 'free stock' },
      { title: 'Kaboompics', url: 'https://kaboompics.com/', description: 'free photos' },
      { title: 'Gratisography', url: 'https://gratisography.com/', description: 'quirky free photos' },
      { title: 'Magnum Photos', url: 'https://www.magnumphotos.com/', description: 'photo agency' },
      { title: '500px', url: 'https://500px.com/', description: 'photo community' },
      { title: 'Flickr', url: 'https://www.flickr.com/', description: 'photo sharing' },
      { title: 'VSCO', url: 'https://vsco.co/', description: 'photo & video' },
      { title: 'Behance Photography', url: 'https://www.behance.net/galleries/photography', description: 'photo portfolios' },
      { title: 'ArtStation', url: 'https://www.artstation.com/', description: 'digital art' },
      { title: 'DeviantArt', url: 'https://www.deviantart.com/', description: 'art community' },
      { title: 'Colossal', url: 'https://www.thisiscolossal.com/', description: 'visual art' },
      { title: 'Booooooom', url: 'https://www.booooooom.com/', description: 'art & photography' },
      { title: 'It\'s Nice That', url: 'https://www.itsnicethat.com/', description: 'creative showcase' },
      { title: 'Creative Boom', url: 'https://www.creativeboom.com/', description: 'creative news' },
      { title: 'Juxtapoz', url: 'https://www.juxtapoz.com/', description: 'art & culture' },
      { title: 'Hi-Fructose', url: 'https://hifructose.com/', description: 'new contemporary art' },
    ]
  },
  // ========== MOTION & 3D ==========
  {
    id: 'motion',
    name: 'motion & animation',
    icon: 'Film',
    sites: [
      { title: 'Motion Design School', url: 'https://motiondesign.school/', description: 'motion tutorials' },
      { title: 'School of Motion', url: 'https://www.schoolofmotion.com/', description: 'motion education' },
      { title: 'Motionographer', url: 'https://motionographer.com/', description: 'motion design' },
      { title: 'Art of the Title', url: 'https://www.artofthetitle.com/', description: 'title sequences' },
      { title: 'Stash Media', url: 'https://www.stashmedia.tv/', description: 'motion showcase' },
      { title: 'LottieFiles', url: 'https://lottiefiles.com/', description: 'animations' },
      { title: 'Rive', url: 'https://rive.app/', description: 'interactive animation' },
      { title: 'GSAP', url: 'https://gsap.com/', description: 'js animation' },
      { title: 'Framer Motion', url: 'https://www.framer.com/motion/', description: 'react animation' },
      { title: 'Theatre.js', url: 'https://www.theatrejs.com/', description: 'animation toolbox' },
      { title: 'Motion One', url: 'https://motion.dev/', description: 'web animation api' },
      { title: 'Anime.js', url: 'https://animejs.com/', description: 'js animation' },
      { title: 'Three.js', url: 'https://threejs.org/', description: '3d library' },
      { title: 'Cavalry', url: 'https://cavalry.scenegroup.co/', description: '2d animation' },
      { title: 'Jitter', url: 'https://jitter.video/', description: 'motion design tool' },
    ]
  },
  {
    id: '3d',
    name: '3d & webgl',
    icon: 'Cpu',
    sites: [
      { title: 'Three.js', url: 'https://threejs.org/', description: 'javascript 3d' },
      { title: 'Bruno Simon', url: 'https://bruno-simon.com/', description: '3d portfolio' },
      { title: 'Awwwards WebGL', url: 'https://www.awwwards.com/websites/webgl/', description: 'webgl sites' },
      { title: 'Codrops', url: 'https://tympanus.net/codrops/', description: 'creative tutorials' },
      { title: 'Theatre.js', url: 'https://www.theatrejs.com/', description: '3d animation' },
      { title: 'Babylon.js', url: 'https://www.babylonjs.com/', description: '3d engine' },
      { title: 'Spline', url: 'https://spline.design/', description: '3d design tool' },
      { title: 'Blender', url: 'https://www.blender.org/', description: 'open source 3d' },
      { title: 'Sketchfab', url: 'https://sketchfab.com/', description: '3d models' },
      { title: 'Poly Haven', url: 'https://polyhaven.com/', description: 'free 3d assets' },
      { title: 'Mixamo', url: 'https://www.mixamo.com/', description: '3d characters' },
      { title: 'CGTrader', url: 'https://www.cgtrader.com/', description: '3d marketplace' },
      { title: 'TurboSquid', url: 'https://www.turbosquid.com/', description: '3d models' },
      { title: 'Free3D', url: 'https://free3d.com/', description: 'free 3d models' },
      { title: 'Pmndrs', url: 'https://pmnd.rs/', description: 'react three fiber' },
    ]
  },
  // ========== FASHION & ECOMMERCE ==========
  {
    id: 'fashion',
    name: 'fashion & style',
    icon: 'Scissors',
    sites: [
      { title: 'Vogue', url: 'https://www.vogue.com/', description: 'fashion magazine' },
      { title: 'Highsnobiety', url: 'https://www.highsnobiety.com/', description: 'streetwear culture' },
      { title: 'Hypebeast', url: 'https://hypebeast.com/', description: 'fashion & culture' },
      { title: 'SSENSE', url: 'https://www.ssense.com/', description: 'luxury fashion' },
      { title: 'Farfetch', url: 'https://www.farfetch.com/', description: 'luxury platform' },
      { title: 'Net-A-Porter', url: 'https://www.net-a-porter.com/', description: 'luxury fashion' },
      { title: 'END.', url: 'https://www.endclothing.com/', description: 'menswear' },
      { title: 'Mr Porter', url: 'https://www.mrporter.com/', description: 'men\'s fashion' },
      { title: 'Grailed', url: 'https://www.grailed.com/', description: 'marketplace' },
      { title: 'StockX', url: 'https://stockx.com/', description: 'sneaker marketplace' },
      { title: 'The Business of Fashion', url: 'https://www.businessoffashion.com/', description: 'industry news' },
      { title: 'i-D', url: 'https://i-d.vice.com/', description: 'fashion culture' },
      { title: 'Dazed', url: 'https://www.dazeddigital.com/', description: 'fashion & culture' },
      { title: 'Another Magazine', url: 'https://www.anothermag.com/', description: 'fashion culture' },
      { title: 'Document Journal', url: 'https://www.documentjournal.com/', description: 'fashion art' },
      // Moodboards & Style Inspiration
      { title: 'Milanote Fashion', url: 'https://milanote.com/templates/moodboards/fashion-moodboard', description: 'fashion moodboards' },
      { title: 'Are.na', url: 'https://www.are.na/', description: 'curated aesthetic channels' },
      { title: 'Tagwalk', url: 'https://www.tagwalk.com/', description: 'runway trend search' },
      { title: 'ShopLook', url: 'https://shoplook.io/', description: 'outfit collages' },
      { title: 'MattoBoard', url: 'https://mattoboard.com/', description: 'drag-drop moodboarding' },
      // Indie & Lowkey Style
      { title: 'Garmentory', url: 'https://www.garmentory.com/', description: 'indie boutiques' },
      { title: 'Need Supply', url: 'https://needsupply.com/', description: 'curated fashion' },
      { title: 'Totokaelo', url: 'https://totokaelo.com/', description: 'avant-garde fashion' },
      { title: 'The Frankie Shop', url: 'https://thefrankieshop.com/', description: 'minimal essentials' },
      { title: 'COS', url: 'https://www.cos.com/', description: 'modern essentials' },
      { title: 'Arket', url: 'https://www.arket.com/', description: 'scandinavian basics' },
      { title: 'Everlane', url: 'https://www.everlane.com/', description: 'transparent pricing' },
      { title: 'Reformation', url: 'https://www.thereformation.com/', description: 'sustainable fashion' },
      { title: 'Aritzia', url: 'https://www.aritzia.com/', description: 'everyday luxury' },
      { title: 'Matches Fashion', url: 'https://www.matchesfashion.com/', description: 'luxury curation' },
    ]
  },
  {
    id: 'ecommerce',
    name: 'ecommerce sites',
    icon: 'ShoppingCart',
    sites: [
      { title: 'Shopify', url: 'https://www.shopify.com/', description: 'ecommerce platform' },
      { title: 'BigCommerce', url: 'https://www.bigcommerce.com/', description: 'commerce platform' },
      { title: 'WooCommerce', url: 'https://woocommerce.com/', description: 'wordpress commerce' },
      { title: 'Stripe', url: 'https://stripe.com/', description: 'payments' },
      { title: 'Square', url: 'https://squareup.com/', description: 'payments' },
      { title: 'Gumroad', url: 'https://gumroad.com/', description: 'sell anything' },
      { title: 'Patreon', url: 'https://www.patreon.com/', description: 'membership platform' },
      { title: 'Ko-fi', url: 'https://ko-fi.com/', description: 'support creators' },
      { title: 'Lemonsqueezy', url: 'https://www.lemonsqueezy.com/', description: 'digital sales' },
      { title: 'Paddle', url: 'https://www.paddle.com/', description: 'saas billing' },
      { title: 'Swell', url: 'https://www.swell.is/', description: 'headless commerce' },
      { title: 'Commerce.js', url: 'https://commercejs.com/', description: 'api-first commerce' },
      { title: 'Medusa', url: 'https://medusajs.com/', description: 'open source commerce' },
      { title: 'Saleor', url: 'https://saleor.io/', description: 'graphql commerce' },
      { title: 'Vendure', url: 'https://www.vendure.io/', description: 'headless commerce' },
    ]
  },
  // ========== FOOD & RESTAURANTS ==========
  {
    id: 'food',
    name: 'food & restaurants',
    icon: 'Utensils',
    sites: [
      // Recipe & Cooking
      { title: 'Serious Eats', url: 'https://www.seriouseats.com/', description: 'culinary science' },
      { title: 'Bon Appétit', url: 'https://www.bonappetit.com/', description: 'food magazine' },
      { title: 'NYT Cooking', url: 'https://cooking.nytimes.com/', description: 'tested recipes' },
      { title: 'Food52', url: 'https://food52.com/', description: 'home cooking' },
      { title: 'Epicurious', url: 'https://www.epicurious.com/', description: 'recipes & tips' },
      { title: 'Tasty', url: 'https://tasty.co/', description: 'quick recipes' },
      { title: 'Half Baked Harvest', url: 'https://www.halfbakedharvest.com/', description: 'comfort food' },
      { title: 'Minimalist Baker', url: 'https://minimalistbaker.com/', description: 'simple recipes' },
      { title: 'Budget Bytes', url: 'https://www.budgetbytes.com/', description: 'budget cooking' },
      { title: 'Smitten Kitchen', url: 'https://smittenkitchen.com/', description: 'home cooking blog' },
      // Restaurant Discovery
      { title: 'Eater', url: 'https://www.eater.com/', description: 'dining guides' },
      { title: 'Infatuation', url: 'https://www.theinfatuation.com/', description: 'restaurant reviews' },
      { title: 'Resy', url: 'https://resy.com/', description: 'reservations' },
      { title: 'OpenTable', url: 'https://www.opentable.com/', description: 'restaurant booking' },
      { title: 'Yelp', url: 'https://www.yelp.com/', description: 'local reviews' },
      // Hidden Gem Restaurants (Aesthetic Sites)
      { title: 'Meals by Genet', url: 'https://mealsbygenet.com/', description: 'ethiopian bistro' },
      { title: 'Cafe Munir', url: 'https://cafemunir.com/', description: 'lebanese hidden gem' },
      { title: 'Redheaded Stranger', url: 'https://redheadedstrangernashville.com/', description: 'nashville bbq' },
      { title: 'Butcher & Bee', url: 'https://butcherandbee.com/', description: 'engaging food focus' },
      { title: 'Mon Lapin', url: 'https://monlapin.ca/', description: 'rustic seasonal montreal' },
      { title: 'Cafe Flora', url: 'https://cafeflora.com/', description: 'seattle vegan gem' },
      { title: 'Eleven Madison Park', url: 'https://www.elevenmadisonpark.com/', description: 'fine dining nyc' },
      { title: 'Noma', url: 'https://noma.dk/', description: 'new nordic cuisine' },
      { title: 'Alinea', url: 'https://www.alinearestaurant.com/', description: 'chicago molecular' },
      { title: 'The French Laundry', url: 'https://www.thomaskeller.com/tfl', description: 'napa fine dining' },
    ]
  },
  // ========== ORIGINAL CATEGORIES ==========
  {
    id: 'privacy',
    name: 'adblock & privacy',
    icon: 'Shield',
    sites: [
      { title: 'uBlock Origin', url: 'https://ublockorigin.com/', description: 'best adblocker' },
      { title: 'Privacy Guides', url: 'https://www.privacyguides.org/', description: 'security handbook' },
      { title: 'FMHY', url: 'https://fmhy.pages.dev/', description: 'the wiki' },
      { title: 'TOS;DR', url: 'https://tosdr.org/', description: 'terms summarized' },
      { title: 'Have I Been Pwned', url: 'https://haveibeenpwned.com/', description: 'breach check' },
      { title: 'Mullvad Browser', url: 'https://mullvad.net/en/browser', description: 'tor without tor' },
      { title: 'Proton', url: 'https://proton.me/', description: 'encrypted suite' },
      { title: 'SimpleLogin', url: 'https://simplelogin.io/', description: 'email aliases' },
      { title: 'KeePassXC', url: 'https://keepassxc.org/', description: 'local passwords' },
      { title: 'Veracrypt', url: 'https://www.veracrypt.fr/', description: 'disk encryption' },
      { title: 'Signal', url: 'https://signal.org/', description: 'secure chat' },
      { title: 'Temp Mail', url: 'https://temp-mail.org/', description: 'disposable email' },
      { title: 'Bitwarden', url: 'https://bitwarden.com/', description: 'password manager' },
      { title: 'Brave Browser', url: 'https://brave.com/', description: 'private browser' },
      { title: 'Firefox', url: 'https://www.mozilla.org/firefox/', description: 'privacy browser' },
      { title: 'DuckDuckGo', url: 'https://duckduckgo.com/', description: 'private search' },
      { title: 'Startpage', url: 'https://www.startpage.com/', description: 'private search' },
      { title: 'Tor Project', url: 'https://www.torproject.org/', description: 'anonymous browsing' },
      { title: 'GrapheneOS', url: 'https://grapheneos.org/', description: 'private android' },
      { title: 'Tails', url: 'https://tails.net/', description: 'amnesic os' },
    ]
  },
  {
    id: 'ai',
    name: 'artificial intelligence',
    icon: 'Bot',
    sites: [
      { title: 'Hugging Face', url: 'https://huggingface.co/', description: 'ai models hub' },
      { title: 'Civitai', url: 'https://civitai.com/', description: 'stable diffusion models' },
      { title: 'ChatGPT', url: 'https://chat.openai.com/', description: 'openai chat' },
      { title: 'Claude', url: 'https://claude.ai/', description: 'anthropic chat' },
      { title: 'Perplexity', url: 'https://www.perplexity.ai/', description: 'ai search' },
      { title: 'Phind', url: 'https://www.phind.com/', description: 'dev search' },
      { title: 'Midjourney', url: 'https://www.midjourney.com/', description: 'art generation' },
      { title: 'DALL-E', url: 'https://openai.com/dall-e-3', description: 'image generation' },
      { title: 'Stable Diffusion', url: 'https://stability.ai/', description: 'open ai art' },
      { title: 'Suno', url: 'https://suno.com/', description: 'ai music' },
      { title: 'ElevenLabs', url: 'https://elevenlabs.io/', description: 'voice synthesis' },
      { title: 'OpenRouter', url: 'https://openrouter.ai/', description: 'model access' },
      { title: 'Replicate', url: 'https://replicate.com/', description: 'run models cloud' },
      { title: 'Runway', url: 'https://runwayml.com/', description: 'ai video tools' },
      { title: 'Pika Labs', url: 'https://pika.art/', description: 'ai video' },
      { title: 'Leonardo AI', url: 'https://leonardo.ai/', description: 'ai art' },
      { title: 'Ideogram', url: 'https://ideogram.ai/', description: 'ai images' },
      { title: 'Krea AI', url: 'https://www.krea.ai/', description: 'real-time ai art' },
      { title: 'Together AI', url: 'https://www.together.ai/', description: 'model api' },
      { title: 'Groq', url: 'https://groq.com/', description: 'fast inference' },
    ]
  },
  {
    id: 'streaming',
    name: 'movies / tv / anime',
    icon: 'Tv',
    sites: [
      { title: 'Stremio', url: 'https://www.stremio.com/', description: 'media center' },
      { title: 'Torrentio', url: 'https://torrentio.strem.fun/', description: 'stremio addon' },
      { title: 'Hianime', url: 'https://hianime.to/', description: 'anime streaming' },
      { title: 'Miruro', url: 'https://www.miruro.tv/', description: 'anime index' },
      { title: 'Piped', url: 'https://piped.video/', description: 'private youtube' },
      { title: 'Invidious', url: 'https://invidious.io/', description: 'youtube frontend' },
      { title: 'AniList', url: 'https://anilist.co/', description: 'anime tracker' },
      { title: 'Simkl', url: 'https://simkl.com/', description: 'tv tracker' },
      { title: 'Letterboxd', url: 'https://letterboxd.com/', description: 'film diary' },
      { title: 'The Movie DB', url: 'https://www.themoviedb.org/', description: 'metadata' },
      { title: 'Trakt', url: 'https://trakt.tv/', description: 'scrobbler' },
      { title: 'JustWatch', url: 'https://www.justwatch.com/', description: 'streaming guide' },
      { title: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com/', description: 'reviews' },
      { title: 'IMDb', url: 'https://www.imdb.com/', description: 'movie database' },
      { title: 'MyAnimeList', url: 'https://myanimelist.net/', description: 'anime database' },
    ]
  },
  {
    id: 'torrenting',
    name: 'files & torrents',
    icon: 'Magnet',
    sites: [
      { title: '1337x', url: 'https://1337x.to/', description: 'general torrents' },
      { title: 'qBittorrent', url: 'https://www.qbittorrent.org/', description: 'best client' },
      { title: 'Real-Debrid', url: 'https://real-debrid.com/', description: 'unrestricted downloader' },
      { title: 'FitGirl Repacks', url: 'https://fitgirl-repacks.site/', description: 'compressed games' },
      { title: 'Anna\'s Archive', url: 'https://annas-archive.org/', description: 'shadow library' },
      { title: 'LibGen', url: 'https://libgen.is/', description: 'book piracy' },
      { title: 'Sci-Hub', url: 'https://sci-hub.se/', description: 'unlock science' },
      { title: 'Internet Archive', url: 'https://archive.org/', description: 'wayback machine' },
      { title: 'JDownloader 2', url: 'https://jdownloader.org/', description: 'download manager' },
      { title: 'Soulseek', url: 'http://www.slsknet.org/', description: 'p2p music' },
      { title: 'Nyaa', url: 'https://nyaa.si/', description: 'anime torrents' },
      { title: 'DoubleDouble', url: 'https://doubledouble.top/', description: 'music ripper' },
      { title: 'Mobilism', url: 'https://forum.mobilism.org/', description: 'mobile apps' },
      { title: 'AudioBookBay', url: 'https://audiobookbay.is/', description: 'audiobooks' },
      { title: 'Rezi', url: 'https://rezi.one/', description: 'ddl site' },
    ]
  },
  {
    id: 'gaming',
    name: 'gaming & emulation',
    icon: 'Gamepad2',
    sites: [
      { title: 'Vimm\'s Lair', url: 'https://vimm.net/', description: 'emulation vault' },
      { title: 'My Abandonware', url: 'https://www.myabandonware.com/', description: 'old games' },
      { title: 'CDRomance', url: 'https://cdromance.com/', description: 'translated roms' },
      { title: 'RetroArch', url: 'https://www.retroarch.com/', description: 'frontend' },
      { title: 'PCSX2', url: 'https://pcsx2.net/', description: 'ps2 emulator' },
      { title: 'RPCS3', url: 'https://rpcs3.net/', description: 'ps3 emulator' },
      { title: 'Dolphin', url: 'https://dolphin-emu.org/', description: 'gamecube/wii' },
      { title: 'Flashpoint', url: 'https://bluemaxima.org/flashpoint/', description: 'flash archive' },
      { title: 'Itch.io', url: 'https://itch.io/', description: 'indie games' },
      { title: 'SteamDB', url: 'https://steamdb.info/', description: 'steam database' },
      { title: 'PCGamingWiki', url: 'https://www.pcgamingwiki.com/', description: 'fixes & mods' },
      { title: 'Nexus Mods', url: 'https://www.nexusmods.com/', description: 'game mods' },
      { title: 'HowLongToBeat', url: 'https://howlongtobeat.com/', description: 'game length' },
      { title: 'EmulatorJS', url: 'https://emulatorjs.org/', description: 'web emulator' },
      { title: 'GOG', url: 'https://www.gog.com/', description: 'drm free games' },
      { title: 'Epic Games', url: 'https://store.epicgames.com/', description: 'free games' },
      { title: 'Humble Bundle', url: 'https://www.humblebundle.com/', description: 'game bundles' },
      { title: 'IsThereAnyDeal', url: 'https://isthereanydeal.com/', description: 'game deals' },
      { title: 'ProtonDB', url: 'https://www.protondb.com/', description: 'linux gaming' },
      { title: 'Ryujinx', url: 'https://ryujinx.org/', description: 'switch emulator' },
    ]
  },
  {
    id: 'tools-web',
    name: 'web tools',
    icon: 'Globe',
    sites: [
      { title: 'Cobalt', url: 'https://cobalt.tools/', description: 'clean media downloader' },
      { title: '12ft Ladder', url: 'https://12ft.io/', description: 'paywall remover' },
      { title: 'Archive.ph', url: 'https://archive.ph/', description: 'snapshot page' },
      { title: 'TinyWow', url: 'https://tinywow.com/', description: 'pdf/img tools' },
      { title: 'JustDeleteMe', url: 'https://backgroundchecks.org/justdeleteme/', description: 'deletion guide' },
      { title: 'Carrd', url: 'https://carrd.co/', description: 'one page sites' },
      { title: 'Gtmetrix', url: 'https://gtmetrix.com/', description: 'speed test' },
      { title: 'VirusTotal', url: 'https://www.virustotal.com/', description: 'malware scan' },
      { title: 'UrlScan', url: 'https://urlscan.io/', description: 'site scanner' },
      { title: 'CyberChef', url: 'https://gchq.github.io/CyberChef/', description: 'data conversion' },
      { title: 'Temp Mail', url: 'https://temp-mail.org/', description: 'disposable email' },
      { title: 'PDF24', url: 'https://tools.pdf24.org/', description: 'pdf tools' },
      { title: 'iLovePDF', url: 'https://www.ilovepdf.com/', description: 'pdf tools' },
      { title: 'Smallpdf', url: 'https://smallpdf.com/', description: 'pdf tools' },
      { title: 'CompressPNG', url: 'https://compresspng.com/', description: 'image compression' },
      { title: 'Remove.bg', url: 'https://www.remove.bg/', description: 'background remover' },
      { title: 'Unscreen', url: 'https://www.unscreen.com/', description: 'video bg remove' },
      { title: 'Cleanup.pictures', url: 'https://cleanup.pictures/', description: 'remove objects' },
      { title: 'Favicon.io', url: 'https://favicon.io/', description: 'favicon generator' },
      { title: 'Meta Tags', url: 'https://metatags.io/', description: 'meta tag generator' },
      // Underrated Free Tools
      { title: 'Penpot', url: 'https://penpot.app/', description: 'open-source figma' },
      { title: 'Google Web Designer', url: 'https://webdesigner.google.com/', description: 'free html5 builder' },
      { title: 'Plasfy', url: 'https://plasfy.com/', description: 'vector graphics' },
      { title: 'Spline', url: 'https://spline.design/', description: '3d web immersive' },
      { title: 'AlternativeTo', url: 'https://alternativeto.net/', description: 'crowdsourced alternatives' },
      { title: 'Raycast', url: 'https://www.raycast.com/', description: 'mac productivity launcher' },
      { title: 'Warp', url: 'https://www.warp.dev/', description: 'modern terminal' },
      { title: 'Fig', url: 'https://fig.io/', description: 'terminal autocomplete' },
      { title: 'Responsively', url: 'https://responsively.app/', description: 'responsive testing' },
      { title: 'Sizzy', url: 'https://sizzy.co/', description: 'browser for devs' },
      { title: 'Polypane', url: 'https://polypane.app/', description: 'dev browser' },
      { title: 'Hoppscotch', url: 'https://hoppscotch.io/', description: 'api testing' },
      { title: 'Insomnia', url: 'https://insomnia.rest/', description: 'api client' },
      { title: 'Bruno', url: 'https://www.usebruno.com/', description: 'offline api client' },
      { title: 'TablePlus', url: 'https://tableplus.com/', description: 'database gui' },
    ]
  },
  {
    id: 'tools-media',
    name: 'image / video / audio',
    icon: 'Image',
    sites: [
      { title: 'Photopea', url: 'https://www.photopea.com/', description: 'web photoshop' },
      { title: 'Squoosh', url: 'https://squoosh.app/', description: 'image compression' },
      { title: 'Ezgif', url: 'https://ezgif.com/', description: 'gif maker' },
      { title: 'Remove.bg', url: 'https://www.remove.bg/', description: 'bg remover' },
      { title: 'Upscayl', url: 'https://upscayl.org/', description: 'ai upscaler' },
      { title: 'Handbrake', url: 'https://handbrake.fr/', description: 'video transcoder' },
      { title: 'FFmpeg', url: 'https://ffmpeg.org/', description: 'media framework' },
      { title: 'Audacity', url: 'https://www.audacityteam.org/', description: 'audio editor' },
      { title: 'Excalidraw', url: 'https://excalidraw.com/', description: 'whiteboard' },
      { title: 'tldraw', url: 'https://www.tldraw.com/', description: 'drawing app' },
      { title: 'Figma', url: 'https://www.figma.com/', description: 'design tool' },
      { title: 'Canva', url: 'https://www.canva.com/', description: 'design made easy' },
      { title: 'Kapwing', url: 'https://www.kapwing.com/', description: 'video editor' },
      { title: 'Clipchamp', url: 'https://clipchamp.com/', description: 'video editor' },
      { title: 'DaVinci Resolve', url: 'https://www.blackmagicdesign.com/products/davinciresolve', description: 'video editing' },
      { title: 'OBS Studio', url: 'https://obsproject.com/', description: 'streaming' },
      { title: 'GIMP', url: 'https://www.gimp.org/', description: 'image editor' },
      { title: 'Inkscape', url: 'https://inkscape.org/', description: 'vector graphics' },
      { title: 'Krita', url: 'https://krita.org/', description: 'digital painting' },
      { title: 'Pixlr', url: 'https://pixlr.com/', description: 'online editor' },
    ]
  },
  {
    id: 'os',
    name: 'os / linux / mobile',
    icon: 'Terminal',
    sites: [
      { title: 'Arch Linux', url: 'https://archlinux.org/', description: 'btw i use arch' },
      { title: 'Debian', url: 'https://www.debian.org/', description: 'universal os' },
      { title: 'Fedora', url: 'https://fedoraproject.org/', description: 'cutting edge' },
      { title: 'Linux Mint', url: 'https://linuxmint.com/', description: 'beginner friendly' },
      { title: 'Ubuntu', url: 'https://ubuntu.com/', description: 'popular linux' },
      { title: 'Pop!_OS', url: 'https://pop.system76.com/', description: 'developer os' },
      { title: 'NixOS', url: 'https://nixos.org/', description: 'declarative linux' },
      { title: 'Ventoy', url: 'https://www.ventoy.net/', description: 'bootable usb' },
      { title: 'Rufus', url: 'https://rufus.ie/', description: 'usb formatter' },
      { title: 'F-Droid', url: 'https://f-droid.org/', description: 'foss android store' },
      { title: 'Aurora Store', url: 'https://auroraoss.com/', description: 'anonymous play store' },
      { title: 'Revanced', url: 'https://revanced.app/', description: 'patched android apps' },
      { title: 'NewPipe', url: 'https://newpipe.net/', description: 'youtube client' },
      { title: 'AltStore', url: 'https://altstore.io/', description: 'ios sideloading' },
      { title: 'Termux', url: 'https://termux.dev/', description: 'android terminal' },
    ]
  },
  {
    id: 'dev',
    name: 'dev & tech',
    icon: 'Code',
    sites: [
      { title: 'GitHub', url: 'https://github.com/', description: 'code hosting' },
      { title: 'GitLab', url: 'https://gitlab.com/', description: 'devops platform' },
      { title: 'Stack Overflow', url: 'https://stackoverflow.com/', description: 'dev help' },
      { title: 'MDN Web Docs', url: 'https://developer.mozilla.org/', description: 'web standard' },
      { title: 'DevDocs', url: 'https://devdocs.io/', description: 'offline docs' },
      { title: 'Roadmap.sh', url: 'https://roadmap.sh/', description: 'learning paths' },
      { title: 'FreeCodeCamp', url: 'https://www.freecodecamp.org/', description: 'learn to code' },
      { title: 'The Odin Project', url: 'https://www.theodinproject.com/', description: 'fullstack curriculum' },
      { title: 'Regex101', url: 'https://regex101.com/', description: 'regex tester' },
      { title: 'Crontab.guru', url: 'https://crontab.guru/', description: 'cron schedules' },
      { title: 'Carbon', url: 'https://carbon.now.sh/', description: 'code screenshots' },
      { title: 'Replit', url: 'https://replit.com/', description: 'online ide' },
      { title: 'CodeSandbox', url: 'https://codesandbox.io/', description: 'web ide' },
      { title: 'StackBlitz', url: 'https://stackblitz.com/', description: 'web ide' },
      { title: 'VSCodium', url: 'https://vscodium.com/', description: 'vscode sans telemetry' },
      { title: 'Docker', url: 'https://www.docker.com/', description: 'containerization' },
      { title: 'Vercel', url: 'https://vercel.com/', description: 'deployment' },
      { title: 'Netlify', url: 'https://www.netlify.com/', description: 'web hosting' },
      { title: 'Railway', url: 'https://railway.app/', description: 'deployment' },
      { title: 'Supabase', url: 'https://supabase.com/', description: 'firebase alternative' },
    ]
  },
  {
    id: 'reading',
    name: 'books / comics / manga',
    icon: 'BookOpen',
    sites: [
      { title: 'MangaDex', url: 'https://mangadex.org/', description: 'manga reader' },
      { title: 'ReadComicsOnline', url: 'https://readcomiconline.li/', description: 'western comics' },
      { title: 'Standard Ebooks', url: 'https://standardebooks.org/', description: 'formatted classics' },
      { title: 'Project Gutenberg', url: 'https://www.gutenberg.org/', description: 'public domain' },
      { title: 'Archive.org Books', url: 'https://archive.org/details/texts', description: 'digitized books' },
      { title: 'Open Library', url: 'https://openlibrary.org/', description: 'book catalog' },
      { title: 'Royal Road', url: 'https://www.royalroad.com/', description: 'web novels' },
      { title: 'AO3', url: 'https://archiveofourown.org/', description: 'fanfiction' },
      { title: 'Goodreads', url: 'https://www.goodreads.com/', description: 'book social' },
      { title: 'Z-Library', url: 'https://z-lib.is/', description: 'ebook library' },
      { title: 'Anna\'s Archive', url: 'https://annas-archive.org/', description: 'book search' },
      { title: 'LibGen', url: 'https://libgen.is/', description: 'library genesis' },
      { title: 'Sci-Hub', url: 'https://sci-hub.se/', description: 'academic papers' },
      { title: 'The Pirate Bay', url: 'https://thepiratebay.org/', description: 'torrents' },
      { title: 'Calibre', url: 'https://calibre-ebook.com/', description: 'ebook management' },
    ]
  },
  {
    id: 'music',
    name: 'music / radio',
    icon: 'Headphones',
    sites: [
      { title: 'Radio Garden', url: 'http://radio.garden/', description: 'global radio' },
      { title: 'NTS Radio', url: 'https://www.nts.live/', description: 'underground radio' },
      { title: 'SomaFM', url: 'https://somafm.com/', description: 'drone/ambient' },
      { title: 'Bandcamp', url: 'https://bandcamp.com/', description: 'support artists' },
      { title: 'Discogs', url: 'https://www.discogs.com/', description: 'vinyl db' },
      { title: 'Rate Your Music', url: 'https://rateyourmusic.com/', description: 'catalog' },
      { title: 'MusicBrainz', url: 'https://musicbrainz.org/', description: 'open metadata' },
      { title: 'Last.fm', url: 'https://www.last.fm/', description: 'scrobbler' },
      { title: 'Every Noise', url: 'https://everynoise.com/', description: 'genre map' },
      { title: 'MyNoise', url: 'https://mynoise.net/', description: 'soundscapes' },
      { title: 'Poolsuite', url: 'https://poolsuite.net/', description: 'retro fm' },
      { title: 'Spotify', url: 'https://open.spotify.com/', description: 'streaming' },
      { title: 'SoundCloud', url: 'https://soundcloud.com/', description: 'music sharing' },
      { title: 'YouTube Music', url: 'https://music.youtube.com/', description: 'music streaming' },
      { title: 'Tidal', url: 'https://tidal.com/', description: 'hifi streaming' },
    ]
  },
  {
    id: 'edu',
    name: 'education',
    icon: 'GraduationCap',
    sites: [
      { title: 'Khan Academy', url: 'https://www.khanacademy.org/', description: 'free learning' },
      { title: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu/', description: 'mit courses' },
      { title: 'Coursera', url: 'https://www.coursera.org/', description: 'online degrees' },
      { title: 'edX', url: 'https://www.edx.org/', description: 'university level' },
      { title: 'Duolingo', url: 'https://www.duolingo.com/', description: 'languages' },
      { title: 'OpenStax', url: 'https://openstax.org/', description: 'textbooks' },
      { title: 'Wolfram Alpha', url: 'https://www.wolframalpha.com/', description: 'computation engine' },
      { title: 'Desmos', url: 'https://www.desmos.com/', description: 'graphing calc' },
      { title: 'Wikipedia', url: 'https://www.wikipedia.org/', description: 'free encyclopedia' },
      { title: 'Brilliant', url: 'https://brilliant.org/', description: 'math & science' },
      { title: 'Codecademy', url: 'https://www.codecademy.com/', description: 'learn coding' },
      { title: 'Udemy', url: 'https://www.udemy.com/', description: 'online courses' },
      { title: 'Skillshare', url: 'https://www.skillshare.com/', description: 'creative classes' },
      { title: 'LinkedIn Learning', url: 'https://www.linkedin.com/learning/', description: 'professional courses' },
      { title: 'Exercism', url: 'https://exercism.org/', description: 'coding practice' },
    ]
  },
  {
    id: 'community',
    name: 'community',
    icon: 'Users',
    sites: [
      { title: 'Lemmy', url: 'https://join-lemmy.org/', description: 'federated reddit' },
      { title: 'Mastodon', url: 'https://joinmastodon.org/', description: 'federated twitter' },
      { title: 'Lobste.rs', url: 'https://lobste.rs/', description: 'tech links' },
      { title: 'Hacker News', url: 'https://news.ycombinator.com/', description: 'startup news' },
      { title: 'Spacehey', url: 'https://spacehey.com/', description: 'myspace clone' },
      { title: 'Neocities', url: 'https://neocities.org/', description: 'free web hosting' },
      { title: 'Discord', url: 'https://discord.com/', description: 'chat' },
      { title: 'Telegram', url: 'https://telegram.org/', description: 'messaging' },
      { title: 'Matrix', url: 'https://matrix.org/', description: 'open network' },
      { title: 'Reddit', url: 'https://www.reddit.com/', description: 'communities' },
      { title: 'Bluesky', url: 'https://bsky.app/', description: 'decentralized social' },
      { title: 'Threads', url: 'https://www.threads.net/', description: 'meta social' },
      { title: 'Cohost', url: 'https://cohost.org/', description: 'social platform' },
      { title: 'Tildes', url: 'https://tildes.net/', description: 'discussion' },
      { title: 'IRC', url: 'https://libera.chat/', description: 'chat network' },
    ]
  },
  {
    id: 'useless',
    name: 'weird & useless',
    icon: 'Smile',
    sites: [
      { title: 'The Useless Web', url: 'https://theuselessweb.com/', description: 'random useless' },
      { title: 'Zombo', url: 'https://zombo.com/', description: 'welcome' },
      { title: 'Pointer Pointer', url: 'https://pointerpointer.com/', description: 'pointers' },
      { title: 'Hacker Typer', url: 'https://hackertyper.com/', description: 'movie hacking' },
      { title: 'Windows 93', url: 'https://www.windows93.net/', description: 'web os' },
      { title: 'Staggering Beauty', url: 'http://www.staggeringbeauty.com/', description: 'flash warning' },
      { title: 'Eelslap', url: 'http://eelslap.com/', description: 'slap' },
      { title: 'Corndog', url: 'https://corndog.io/', description: 'corn dogs' },
      { title: 'Zoom Quilt', url: 'https://zoomquilt.org/', description: 'infinite zoom' },
      { title: 'Quick, Draw!', url: 'https://quickdraw.withgoogle.com/', description: 'ai pictionary' },
      { title: 'Weavesilk', url: 'http://weavesilk.com/', description: 'generative art' },
      { title: 'Patatap', url: 'https://www.patatap.com/', description: 'sound kit' },
      { title: 'Incredibox', url: 'https://www.incredibox.com/', description: 'beatbox game' },
      { title: 'This is Sand', url: 'https://thisissand.com/', description: 'sand art' },
      { title: 'Find the Invisible Cow', url: 'https://findtheinvisiblecow.com/', description: 'moo game' },
    ]
  },
  {
    id: 'history',
    name: 'history & data',
    icon: 'Landmark',
    sites: [
      { title: 'Our World in Data', url: 'https://ourworldindata.org/', description: 'stats' },
      { title: 'Bellingcat', url: 'https://www.bellingcat.com/', description: 'osint' },
      { title: 'Internet Artifacts', url: 'https://neal.fun/internet-artifacts/', description: 'web museum' },
      { title: 'Library of Congress', url: 'https://www.loc.gov/', description: 'archives' },
      { title: 'WikiLeaks', url: 'https://wikileaks.org/', description: 'leaks' },
      { title: 'Gapminder', url: 'https://www.gapminder.org/', description: 'world view' },
      { title: 'CIA FOIA', url: 'https://www.cia.gov/readingroom/', description: 'declassified' },
      { title: 'Internet Archive', url: 'https://archive.org/', description: 'wayback machine' },
      { title: 'WorldCat', url: 'https://www.worldcat.org/', description: 'library catalog' },
      { title: 'Google Dataset Search', url: 'https://datasetsearch.research.google.com/', description: 'datasets' },
      { title: 'Statista', url: 'https://www.statista.com/', description: 'statistics' },
      { title: 'Data.gov', url: 'https://data.gov/', description: 'us open data' },
      { title: 'World Bank Data', url: 'https://data.worldbank.org/', description: 'global data' },
      { title: 'NASA Open Data', url: 'https://data.nasa.gov/', description: 'space data' },
      { title: 'Old Maps Online', url: 'https://www.oldmapsonline.org/', description: 'historical maps' },
    ]
  },
  // ========== ADDITIONAL CATEGORIES ==========
  {
    id: 'productivity',
    name: 'productivity',
    icon: 'Zap',
    sites: [
      { title: 'Notion', url: 'https://www.notion.so/', description: 'workspace' },
      { title: 'Obsidian', url: 'https://obsidian.md/', description: 'knowledge base' },
      { title: 'Logseq', url: 'https://logseq.com/', description: 'outliner' },
      { title: 'Todoist', url: 'https://todoist.com/', description: 'task manager' },
      { title: 'Linear', url: 'https://linear.app/', description: 'issue tracking' },
      { title: 'Trello', url: 'https://trello.com/', description: 'kanban boards' },
      { title: 'Asana', url: 'https://asana.com/', description: 'project management' },
      { title: 'ClickUp', url: 'https://clickup.com/', description: 'productivity platform' },
      { title: 'Airtable', url: 'https://www.airtable.com/', description: 'database builder' },
      { title: 'Coda', url: 'https://coda.io/', description: 'docs + apps' },
      { title: 'Craft', url: 'https://www.craft.do/', description: 'documents' },
      { title: 'Bear', url: 'https://bear.app/', description: 'notes' },
      { title: 'Things 3', url: 'https://culturedcode.com/things/', description: 'task manager' },
      { title: 'Raindrop', url: 'https://raindrop.io/', description: 'bookmarks' },
      { title: 'Pocket', url: 'https://getpocket.com/', description: 'save articles' },
      // Aesthetic Minimal Hidden Gems
      { title: 'Superlist', url: 'https://www.superlist.com/', description: 'sleek wunderlist successor' },
      { title: 'Reflect', url: 'https://reflect.app/', description: 'minimal journaling + ai' },
      { title: 'Flocus', url: 'https://flocus.com/', description: 'aesthetic dashboard' },
      { title: 'Headway', url: 'https://www.headway.com/', description: 'book summaries' },
      { title: 'Capacities', url: 'https://capacities.io/', description: 'object-based notes' },
      { title: 'Anytype', url: 'https://anytype.io/', description: 'local-first workspace' },
      { title: 'Tana', url: 'https://tana.inc/', description: 'supertag workspace' },
      { title: 'Mem', url: 'https://mem.ai/', description: 'ai-powered notes' },
      { title: 'Routine', url: 'https://www.routine.co/', description: 'calendar + tasks' },
      { title: 'Akiflow', url: 'https://akiflow.com/', description: 'time blocking' },
      { title: 'Reclaim', url: 'https://reclaim.ai/', description: 'ai scheduling' },
      { title: 'Motion', url: 'https://www.usemotion.com/', description: 'ai calendar' },
      { title: 'Sunsama', url: 'https://sunsama.com/', description: 'daily planner' },
      { title: 'Centered', url: 'https://www.centered.app/', description: 'flow state app' },
      { title: 'Pomofocus', url: 'https://pomofocus.io/', description: 'clean pomodoro' },
    ]
  },
  {
    id: 'startup',
    name: 'startup & business',
    icon: 'Rocket',
    sites: [
      { title: 'Product Hunt', url: 'https://www.producthunt.com/', description: 'new products' },
      { title: 'Indie Hackers', url: 'https://www.indiehackers.com/', description: 'founder community' },
      { title: 'Y Combinator', url: 'https://www.ycombinator.com/', description: 'startup accelerator' },
      { title: 'AngelList', url: 'https://angel.co/', description: 'startup jobs' },
      { title: 'Crunchbase', url: 'https://www.crunchbase.com/', description: 'startup database' },
      { title: 'TechCrunch', url: 'https://techcrunch.com/', description: 'tech news' },
      { title: 'The Verge', url: 'https://www.theverge.com/', description: 'tech news' },
      { title: 'Wired', url: 'https://www.wired.com/', description: 'tech culture' },
      { title: 'Stratechery', url: 'https://stratechery.com/', description: 'tech analysis' },
      { title: 'First Round Review', url: 'https://review.firstround.com/', description: 'startup advice' },
      { title: 'a]16z', url: 'https://a16z.com/', description: 'vc insights' },
      { title: 'Lenny\'s Newsletter', url: 'https://www.lennysnewsletter.com/', description: 'product advice' },
      { title: 'Startup School', url: 'https://www.startupschool.org/', description: 'yc course' },
      { title: 'Pioneer', url: 'https://pioneer.app/', description: 'startup tournament' },
      { title: 'Levels.fyi', url: 'https://www.levels.fyi/', description: 'tech salaries' },
    ]
  },
  {
    id: 'news',
    name: 'news & magazines',
    icon: 'Newspaper',
    sites: [
      { title: 'The Guardian', url: 'https://www.theguardian.com/', description: 'world news' },
      { title: 'Reuters', url: 'https://www.reuters.com/', description: 'news wire' },
      { title: 'AP News', url: 'https://apnews.com/', description: 'associated press' },
      { title: 'NPR', url: 'https://www.npr.org/', description: 'public radio' },
      { title: 'BBC', url: 'https://www.bbc.com/', description: 'british news' },
      { title: 'Al Jazeera', url: 'https://www.aljazeera.com/', description: 'world news' },
      { title: 'Ars Technica', url: 'https://arstechnica.com/', description: 'tech news' },
      { title: 'The Atlantic', url: 'https://www.theatlantic.com/', description: 'magazine' },
      { title: 'The New Yorker', url: 'https://www.newyorker.com/', description: 'magazine' },
      { title: 'Rest of World', url: 'https://restofworld.org/', description: 'global tech' },
      { title: '404 Media', url: 'https://www.404media.co/', description: 'tech journalism' },
      { title: 'Ground News', url: 'https://ground.news/', description: 'news comparison' },
      { title: 'AllSides', url: 'https://www.allsides.com/', description: 'balanced news' },
      { title: 'Hacker News', url: 'https://news.ycombinator.com/', description: 'tech discussion' },
      { title: 'Slashdot', url: 'https://slashdot.org/', description: 'tech news' },
    ]
  },
  {
    id: 'crypto',
    name: 'crypto & web3',
    icon: 'Bitcoin',
    sites: [
      { title: 'CoinGecko', url: 'https://www.coingecko.com/', description: 'crypto prices' },
      { title: 'CoinMarketCap', url: 'https://coinmarketcap.com/', description: 'market cap' },
      { title: 'DeFi Llama', url: 'https://defillama.com/', description: 'defi tvl' },
      { title: 'Etherscan', url: 'https://etherscan.io/', description: 'eth explorer' },
      { title: 'OpenSea', url: 'https://opensea.io/', description: 'nft marketplace' },
      { title: 'Uniswap', url: 'https://uniswap.org/', description: 'dex' },
      { title: 'Aave', url: 'https://aave.com/', description: 'lending' },
      { title: 'Metamask', url: 'https://metamask.io/', description: 'wallet' },
      { title: 'Rainbow', url: 'https://rainbow.me/', description: 'eth wallet' },
      { title: 'Dune', url: 'https://dune.com/', description: 'blockchain analytics' },
      { title: 'Mirror', url: 'https://mirror.xyz/', description: 'web3 publishing' },
      { title: 'ENS', url: 'https://ens.domains/', description: 'eth domains' },
      { title: 'Farcaster', url: 'https://www.farcaster.xyz/', description: 'web3 social' },
      { title: 'Zora', url: 'https://zora.co/', description: 'nft platform' },
      { title: 'Foundation', url: 'https://foundation.app/', description: 'art market' },
    ]
  },
  {
    id: 'travel',
    name: 'travel & maps',
    icon: 'Map',
    sites: [
      { title: 'Google Maps', url: 'https://maps.google.com/', description: 'maps' },
      { title: 'OpenStreetMap', url: 'https://www.openstreetmap.org/', description: 'open maps' },
      { title: 'Google Flights', url: 'https://www.google.com/flights', description: 'flight search' },
      { title: 'Skyscanner', url: 'https://www.skyscanner.com/', description: 'flight comparison' },
      { title: 'Rome2rio', url: 'https://www.rome2rio.com/', description: 'travel routes' },
      { title: 'Seat Guru', url: 'https://www.seatguru.com/', description: 'airplane seats' },
      { title: 'FlightAware', url: 'https://flightaware.com/', description: 'flight tracker' },
      { title: 'Flightradar24', url: 'https://www.flightradar24.com/', description: 'live flights' },
      { title: 'Airbnb', url: 'https://www.airbnb.com/', description: 'accommodation' },
      { title: 'Booking.com', url: 'https://www.booking.com/', description: 'hotels' },
      { title: 'Hostelworld', url: 'https://www.hostelworld.com/', description: 'hostels' },
      { title: 'TripAdvisor', url: 'https://www.tripadvisor.com/', description: 'reviews' },
      { title: 'Atlas Obscura', url: 'https://www.atlasobscura.com/', description: 'hidden places' },
      { title: 'Nomad List', url: 'https://nomadlist.com/', description: 'remote work cities' },
      { title: 'Wanderlog', url: 'https://wanderlog.com/', description: 'trip planner' },
    ]
  },
  // ========== SHOPPING & DISCOVERY ==========
  {
    id: 'shopping-discovery',
    name: 'shopping & discovery',
    icon: 'ShoppingCart',
    sites: [
      { title: 'Amazon Interesting Finds', url: 'https://www.amazon.com/interestingfinds', description: 'curated discoveries' },
      { title: 'Amazon Movers & Shakers', url: 'https://www.amazon.com/gp/movers-and-shakers', description: 'trending products' },
      { title: 'Amazon Best Sellers', url: 'https://www.amazon.com/Best-Sellers/zgbs', description: 'top products' },
      { title: 'Amazon New Releases', url: 'https://www.amazon.com/gp/new-releases', description: 'just launched' },
      { title: 'Amazon Launchpad', url: 'https://www.amazon.com/launchpad', description: 'startup products' },
      { title: 'Product Hunt', url: 'https://www.producthunt.com/', description: 'new tech products' },
      { title: 'This Is Why Im Broke', url: 'https://www.thisiswhyimbroke.com/', description: 'weird finds' },
      { title: 'Uncrate', url: 'https://uncrate.com/', description: 'gear for guys' },
      { title: 'Cool Material', url: 'https://coolmaterial.com/', description: 'cool products' },
      { title: 'Bless This Stuff', url: 'https://www.blessthisstuff.com/', description: 'curated products' },
      { title: 'Huckberry', url: 'https://huckberry.com/', description: 'outdoor gear' },
      { title: 'Grommet', url: 'https://www.thegrommet.com/', description: 'unique products' },
      { title: 'Fancy', url: 'https://fancy.com/', description: 'discover things' },
      { title: 'Canopy', url: 'https://canopy.co/', description: 'amazon curated' },
      { title: 'The Strategist', url: 'https://nymag.com/strategist/', description: 'product reviews' },
    ]
  },
  // ========== PERSONAL PORTFOLIOS ==========
  {
    id: 'portfolios',
    name: 'personal portfolios',
    icon: 'User',
    sites: [
      // Iconic & Viral All-Time Classics
      { title: 'Bruno Simon', url: 'https://bruno-simon.com/', description: '3d toy car world' },
      { title: 'Robby Leonardi', url: 'http://www.rleonardi.com/interactive-resume/', description: 'mario-style game portfolio' },
      { title: 'Lynn Fisher', url: 'https://lynnandtonic.com/', description: 'quirky annual redesigns' },
      { title: 'Active Theory', url: 'https://activetheory.net/', description: 'innovative experiments' },
      
      // Awwwards Winners & Top Nominees 2025
      { title: 'Max Milkin', url: 'https://maxmilkin.com/', description: 'awwwards winner' },
      { title: 'Paolo Vendramini', url: 'https://paolovendramini.com/', description: 'dev award winner' },
      { title: 'Aziz Khaldi', url: 'https://azizkhaldi.com/', description: 'awwwards portfolio' },
      { title: 'Creative Giants', url: 'https://creativegiants.com/', description: 'creative studio' },
      { title: 'Bart Kolenda', url: 'https://bartkolenda.com/', description: 'awwwards nominee' },
      { title: 'Phantom.Land', url: 'https://phantom.land/', description: 'surreal 3d landscapes' },
      { title: 'Caffè Design', url: 'https://caffedesign.it/', description: 'italian design' },
      { title: 'Form&Fun Studio', url: 'https://formandfun.studio/', description: 'playful design' },
      { title: 'Jam Area', url: 'https://jamarea.com/', description: 'creative studio' },
      { title: 'Diego Sevilla', url: 'https://diegosevilla.com/', description: '2025 portfolio' },
      { title: 'Cyd Stumpel', url: 'https://cydstumpel.com/', description: '2025 portfolio' },
      { title: 'Rauno Freiberg', url: 'https://raunofreiberg.com/', description: 'smooth ui experiments' },
      
      // Timeless Classics & Viral Hits
      { title: 'Wildy Riftian', url: 'https://www.wildyriftian.com/', description: 'creative portfolio' },
      { title: 'Jon Howell', url: 'https://www.jonhowell.com/', description: 'designer portfolio' },
      { title: 'Abhijitrout', url: 'https://www.abhijitrout.in/', description: 'indian creative' },
      
      // Framer-Built Standouts
      { title: 'Glenn Catteeuw', url: 'https://glenncatteeuw.com/', description: 'framer modern' },
      { title: 'Wassim Gharbi', url: 'https://gharbi.me/', description: 'interactive portfolio' },
      { title: 'Sue Park', url: 'https://spark7515.com/', description: 'framer designer' },
      { title: 'Lorenzo Cabra', url: 'https://bylorenzo.xyz/', description: 'creative dev' },
      { title: 'Aman Satyawani', url: 'https://satyawani.in/', description: 'minimal portfolio' },
      { title: 'LowKeyDevs', url: 'https://www.lowkeydev.me/', description: 'dev portfolio' },
      { title: 'Bruce Cao', url: 'https://brucecao.com/', description: 'interactive dev' },
      { title: 'Judy Zhou', url: 'https://judyzhou.me/', description: 'designer portfolio' },
      { title: 'Yuvraj Dev', url: 'https://yuvraj-dev.me/', description: 'developer' },
      
      // Over-the-Top Artsy & Experimental
      { title: 'Marco', url: 'https://www.marco.fyi/', description: 'insane interactions' },
      { title: 'Henri Heymans', url: 'https://henriheymans.com/', description: 'creative dev vibes' },
      { title: 'Henri Lu', url: 'https://henrilu.com/', description: 'ui art direction' },
      { title: 'Lu Yu', url: 'https://luyu.design/', description: 'design portfolio' },
      { title: 'Joseph San', url: 'https://josephsan.com/', description: 'motion & kinetic' },
      { title: '1:09 Ichiki', url: 'https://109ichiki.com/', description: 'fluorescent illustrations' },
      { title: 'ByChudy (Miłosz Chudy)', url: 'https://bychudy.com/', description: 'kinetic motion' },
      { title: 'Alice Lee', url: 'https://byalicelee.com/', description: 'colorful illustrator' },
      { title: 'Lauren Hom', url: 'https://laurenhom.com/', description: 'hom sweet hom lettering' },
      { title: 'Studio Feixen', url: 'https://studiofeixen.ch/', description: 'vibrant chaotic fun' },
      
      // Developer & Designer Portfolios
      { title: 'Roman Jean-Elie', url: 'https://romanjeanelie.com/', description: 'creative developer' },
      { title: 'Chris Foy', url: 'https://chrisfoy.com/', description: 'bold portfolio' },
      { title: 'Andre Cirieco', url: 'https://andrecirieco.com/', description: 'developer portfolio' },
      { title: 'Elliott Mangham', url: 'https://elliottmangham.com/', description: 'creative dev' },
      { title: 'Kele Dobrinski', url: 'https://keledobrinski.com/', description: 'designer dev' },
      { title: 'Marga Peces', url: 'https://margapeces.com/', description: 'creative portfolio' },
      { title: 'Emilie Druss', url: 'https://emiliedruss.com/', description: 'designer' },
      { title: 'Robin', url: 'https://robin.fr/', description: 'freelance interaction' },
      { title: 'Moritz', url: 'https://moritz.com/', description: 'detailed case studies' },
      
      // Personality-Driven Gems
      { title: 'Alana Goyal', url: 'https://alanagoyal.com/', description: 'apple notes interactive' },
      { title: 'Pedro Stolf', url: 'https://pedrostolf.com/', description: 'creative portfolio' },
      { title: 'Kris Puckett', url: 'https://krispuckett.com/', description: 'shader experiments' },
      { title: 'Emmanuel Krissemmy', url: 'https://www.krissemmy.com/', description: 'creative dev' },
      { title: 'Cade Martin', url: 'https://cademartin.com/', description: 'book-like photography' },
      
      // Original Developer Portfolios
      { title: 'Brittany Chiang', url: 'https://brittanychiang.com/', description: 'software engineer' },
      { title: 'Josh Comeau', url: 'https://www.joshwcomeau.com/', description: 'developer educator' },
      { title: 'Cassie Evans', url: 'https://www.cassie.codes/', description: 'creative developer' },
      { title: 'Jhey Tompkins', url: 'https://jhey.dev/', description: 'creative developer' },
      { title: 'Sara Soueidan', url: 'https://www.sarasoueidan.com/', description: 'frontend dev' },
      { title: 'Adham Dannaway', url: 'https://www.adhamdannaway.com/', description: 'ui designer' },
      { title: 'Tobias Ahlin', url: 'https://tobiasahlin.com/', description: 'designer' },
      { title: 'Jack Jeznach', url: 'https://jacekjeznach.com/', description: 'creative dev' },
      { title: 'Olaolu Olawuyi', url: 'https://olaolu.dev/', description: 'frontend dev' },
      { title: 'Yuri Artiukh', url: 'https://akella.one/', description: 'webgl artist' },
      { title: 'Lee Robinson', url: 'https://leerob.io/', description: 'vercel vp' },
      { title: 'Wes Bos', url: 'https://wesbos.com/', description: 'web developer' },
      { title: 'Dan Abramov', url: 'https://overreacted.io/', description: 'react core' },
      { title: 'Kent C. Dodds', url: 'https://kentcdodds.com/', description: 'educator' },
      { title: 'Tania Rascia', url: 'https://www.taniarascia.com/', description: 'developer' },
      { title: 'Max Böck', url: 'https://mxb.dev/', description: 'web developer' },
      { title: 'Ahmad Shadeed', url: 'https://ishadeed.com/', description: 'css expert' },
      { title: 'Stephanie Eckles', url: 'https://thinkdobecreate.com/', description: 'css dev' },
      { title: 'Chen Hui Jing', url: 'https://chenhuijing.com/', description: 'frontend dev' },
      { title: 'Florin Pop', url: 'https://www.florin-pop.com/', description: 'developer' },
      { title: 'Jason Lengstorf', url: 'https://www.jason.af/', description: 'developer' },
      { title: 'Shawn Wang', url: 'https://www.swyx.io/', description: 'dx engineer' },
    ]
  },
  // ========== PORTFOLIO INSPIRATION SOURCES ==========
  {
    id: 'portfolio-inspiration',
    name: 'portfolio galleries',
    icon: 'Star',
    sites: [
      { title: 'Awwwards Portfolios', url: 'https://www.awwwards.com/websites/portfolio/', description: 'award-winning portfolios' },
      { title: 'Framer Gallery', url: 'https://www.framer.com/gallery/categories/portfolio', description: 'framer portfolios' },
      { title: 'Muzli Top 100', url: 'https://muz.li/blog/top-100-most-creative-and-unique-portfolio-websites-of-2025/', description: 'creative portfolios 2025' },
      { title: 'Pafolios', url: 'https://pafolios.com/', description: 'product design portfolios' },
      { title: 'SiteBuilderReport', url: 'https://www.sitebuilderreport.com/inspiration/portfolio-websites', description: 'portfolio inspirations' },
      { title: 'The FWA', url: 'https://thefwa.com/', description: 'experimental sites' },
    ]
  },
];

// Export for use
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { categories };
}

